# Generated by Django 5.1.4 on 2024-12-30 23:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(choices=[('blanco', 'Blanco'), ('negro', 'Negro'), ('gris', 'Gris'), ('rojo', 'Rojo'), ('azul', 'Azul'), ('verde', 'Verde')], max_length=20)),
                ('año', models.PositiveIntegerField()),
                ('kilometraje_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GastoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('combustible', 'Combustible'), ('reparacion', 'Reparación'), ('peaje', 'Peaje')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometraje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('litros', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='transporte.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]$')])),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe ser chileno', regex='^\\+?569\\d{8}$')])),
                ('vehiculo_asignado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chofer_actual', to='transporte.vehiculo')),
            ],
        ),
    ]
