# Generated by Django 5.1.4 on 2024-12-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_stock_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
