# Generated by Django 5.1.4 on 2025-01-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimientoinventario_descripcion'),
        ('inventario', '0003_alter_movimientoinventario_options_and_more'),
    ]

    operations = [
    ]
