# Generated by Django 5.1.4 on 2024-12-31 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del lote (ej: LOT-2024-001)', max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('ACT', 'Activo'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='PEN', max_length=3)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='compras.ordencompra')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('merma_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='produccion.lote')),
            ],
            options={
                'ordering': ['-fecha', '-hora_inicio'],
                'unique_together': {('lote', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='ItemProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calidad', models.CharField(choices=[('PRIMERA', 'Primera'), ('SEGUNDA', 'Segunda'), ('TERCERA', 'Tercera')], max_length=20)),
                ('peso_unidad', models.DecimalField(decimal_places=2, help_text='Peso promedio por unidad en gramos', max_digits=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='inventario.producto')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='produccion.producciondiaria')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
