# Generated by Django 5.1.4 on 2025-01-01 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemproduccion',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='producciondiaria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itemproduccion',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='itemproduccion',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='itemproduccion',
            name='peso_unidad',
        ),
        migrations.AddField(
            model_name='itemproduccion',
            name='precio_unidad',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio acordado por unidad para este trabajador', max_digits=10),
        ),
        migrations.AddField(
            model_name='producciondiaria',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='producciondiaria',
            unique_together={('lote', 'fecha', 'trabajador')},
        ),
    ]
