# Generated by Django 5.1.4 on 2024-12-30 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesoproduccion',
            name='merma',
        ),
        migrations.RemoveField(
            model_name='procesoproduccion',
            name='notas_merma',
        ),
        migrations.AlterField(
            model_name='procesoproduccion',
            name='peso_procesado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Peso total procesado hasta el momento', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='procesoproduccion',
            name='peso_total',
            field=models.DecimalField(decimal_places=2, help_text='Peso total recibido de la orden de compra', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producciondiaria',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
