# Generated by Django 5.1.4 on 2025-01-01 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_itemproduccion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producciondiaria',
            unique_together={('lote', 'fecha', 'trabajador', 'hora_inicio')},
        ),
        migrations.AlterField(
            model_name='producciondiaria',
            name='merma_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
