# Generated by Django 5.1.4 on 2025-01-01 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_itemproduccion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producciondiaria',
            options={'ordering': ['-fecha', '-hora_inicio']},
        ),
        migrations.RemoveField(
            model_name='producciondiaria',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='producciondiaria',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producciondiaria',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador'),
        ),
    ]
