# Generated by Django 5.1.4 on 2025-01-02 00:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('produccion', '0003_alter_producciondiaria_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producciondiaria',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Procesar'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Producción Completada'), ('ANULADO', 'Producción Anulada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='producciondiaria',
            name='fecha_actualizacion_inventario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producciondiaria',
            name='inventario_actualizado',
            field=models.BooleanField(default=False, help_text='Indica si los movimientos de inventario ya fueron procesados'),
        ),
        migrations.AlterField(
            model_name='producciondiaria',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MateriaPrimaUtilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_primas', to='produccion.producciondiaria')),
                ('producto', models.ForeignKey(limit_choices_to={'tipo_producto': 'MATERIA'}, on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_producciones', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Materia Prima Utilizada',
                'verbose_name_plural': 'Materias Primas Utilizadas',
                'unique_together': {('produccion', 'producto')},
            },
        ),
    ]
