# Generated by Django 5.1.4 on 2025-01-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_producciondiaria_options_and_more'),
        ('produccion', '0003_eliminar_datos'),
        ('produccion', '0004_producciondiaria_estado_and_more'),
    ]

    operations = [
    ]
