# Generated by Django 5.1.4 on 2025-01-06 01:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del lote (ej: LOT-2024-001)', max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('ACT', 'Activo'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='PEN', max_length=3)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='compras.ordencompra')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('merma_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Procesar'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Producción Completada'), ('ANULADO', 'Producción Anulada')], default='PENDIENTE', max_length=20)),
                ('inventario_actualizado', models.BooleanField(default=False, help_text='Indica si los movimientos de inventario ya fueron procesados')),
                ('fecha_actualizacion_inventario', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='produccion.lote')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-hora_inicio'],
                'unique_together': {('lote', 'fecha', 'trabajador', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='ItemProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unidad', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio acordado por unidad para este trabajador', max_digits=10)),
                ('calidad', models.CharField(choices=[('PRIMERA', 'Primera'), ('SEGUNDA', 'Segunda'), ('TERCERA', 'Tercera')], max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='inventario.producto')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='produccion.producciondiaria')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrimaUtilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(limit_choices_to={'tipo_producto': 'MATERIA'}, on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_producciones', to='inventario.producto')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_primas', to='produccion.producciondiaria')),
            ],
            options={
                'verbose_name': 'Materia Prima Utilizada',
                'verbose_name_plural': 'Materias Primas Utilizadas',
                'unique_together': {('produccion', 'producto')},
            },
        ),
    ]
