# Generated by Django 5.1.4 on 2024-12-29 14:10

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_producto_productoproveedor'),  # Reemplaza con el nombre exacto de tu migración 0002
        ('compras', '0003_alter_detalleordencompra_subtotal_and_more'),  # Reemplaza con el nombre exacto de tu migración 0003
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoProveedor',
        ),
    ]
