# Generated by Django 5.1.4 on 2024-12-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_detalleordencompra_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoproveedor',
            name='producto',
        ),
        migrations.AlterUniqueTogether(
            name='productoproveedor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productoproveedor',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ProductoProveedor',
        ),
    ]
