# Generated by Django 5.1.4 on 2024-12-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20241229_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
