# Generated by Django 5.1.4 on 2025-01-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('compras', '0004_remove_productoproveedor_producto_and_more'),
        ('compras', '0005_delete_producto'),
    ]

    operations = [
    ]
