# Generated by Django 5.1.4 on 2025-01-01 13:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLANTA', 'Trabajador de Planta'), ('TEMPORERO', 'Trabajador Temporero')], help_text='Tipo de trabajador (planta o temporero)', max_length=10)),
                ('rut', models.CharField(help_text='RUT del trabajador con formato XX.XXX.XXX-X', max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('contacto_emergencia', models.CharField(help_text='Nombre y teléfono del contacto de emergencia', max_length=100)),
                ('estado', models.BooleanField(default=True, help_text='Estado activo/inactivo del trabajador')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_trabajador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ContratoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Contrato Indefinido'), ('PLAZO_FIJO', 'Plazo Fijo')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, help_text='Solo para contratos a plazo fijo', null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('horas_semanales', models.PositiveSmallIntegerField(default=45, help_text='Horas de trabajo semanales acordadas')),
                ('bonificacion_colacion', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bonificacion_movilidad', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('otros_bonos', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('trabajador', models.ForeignKey(limit_choices_to={'tipo': 'PLANTA'}, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='rrhh.trabajador')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TarifaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unidad', models.DecimalField(decimal_places=2, help_text='Precio por unidad producida', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='inventario.producto')),
                ('trabajador', models.ForeignKey(limit_choices_to={'tipo': 'TEMPORERO'}, on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='rrhh.trabajador')),
            ],
            options={
                'verbose_name': 'Tarifa de Producción',
                'verbose_name_plural': 'Tarifas de Producción',
                'ordering': ['trabajador', 'producto', '-fecha_inicio'],
                'unique_together': {('trabajador', 'producto', 'fecha_inicio')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, help_text='Horas extras trabajadas', max_digits=4)),
                ('observaciones', models.TextField(blank=True)),
                ('trabajador', models.ForeignKey(limit_choices_to={'tipo': 'PLANTA'}, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='rrhh.trabajador')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', '-hora_entrada'],
                'unique_together': {('trabajador', 'fecha')},
            },
        ),
    ]
