# Generated by Django 5.1.4 on 2025-01-06 01:52

import django.db.models.deletion
import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del trabajador', max_length=200)),
                ('rut', models.CharField(help_text='Formato: XX.XXX.XXX-X', max_length=12, unique=True, validators=[rrhh.models.validar_rut_chileno])),
                ('categoria', models.CharField(choices=[('PL', 'Planta'), ('CO', 'Conductor'), ('CA', 'Carguero'), ('TE', 'Temporal')], help_text='Categoría del trabajador', max_length=2)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del trabajador')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(help_text='Nombre o código del producto', max_length=100)),
                ('cantidad', models.IntegerField(help_text='Cantidad de unidades producidas')),
                ('valor_unitario', models.DecimalField(decimal_places=0, help_text='Valor por unidad en pesos chilenos', max_digits=8)),
                ('fecha', models.DateField(help_text='Fecha de la producción')),
                ('total_calculado', models.DecimalField(decimal_places=0, help_text='Total calculado (cantidad * valor_unitario)', max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro de la producción')),
                ('trabajador', models.ForeignKey(help_text='Trabajador que realizó la producción', on_delete=django.db.models.deletion.PROTECT, related_name='producciones_temporales', to='rrhh.trabajador')),
            ],
            options={
                'verbose_name': 'Producción Temporal',
                'verbose_name_plural': 'Producciones Temporales',
                'ordering': ['-fecha', 'trabajador'],
            },
        ),
        migrations.CreateModel(
            name='PagoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(help_text='Fecha de inicio de la semana')),
                ('semana_fin', models.DateField(help_text='Fecha de fin de la semana')),
                ('total_unidades', models.IntegerField(help_text='Total de unidades producidas en la semana')),
                ('monto_total', models.DecimalField(decimal_places=0, help_text='Monto total del pago en pesos chilenos', max_digits=10)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('AN', 'Anulado')], default='PE', help_text='Estado actual del pago', max_length=2)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del pago temporal')),
                ('trabajador', models.ForeignKey(help_text='Trabajador temporal al que corresponde el pago', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_temporales', to='rrhh.trabajador')),
            ],
            options={
                'verbose_name': 'Pago Temporal',
                'verbose_name_plural': 'Pagos Temporales',
                'ordering': ['-semana_inicio', 'trabajador'],
                'unique_together': {('trabajador', 'semana_inicio', 'semana_fin')},
            },
        ),
        migrations.CreateModel(
            name='PagoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Mes correspondiente al pago')),
                ('monto', models.DecimalField(decimal_places=0, help_text='Monto del pago en pesos chilenos', max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del pago')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('AN', 'Anulado')], default='PE', help_text='Estado actual del pago', max_length=2)),
                ('trabajador', models.ForeignKey(help_text='Trabajador al que corresponde el pago', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_mensuales', to='rrhh.trabajador')),
            ],
            options={
                'verbose_name': 'Pago Mensual',
                'verbose_name_plural': 'Pagos Mensuales',
                'ordering': ['-mes', 'trabajador'],
                'unique_together': {('trabajador', 'mes')},
            },
        ),
    ]
