# Generated by Django 5.1.4 on 2025-01-01 19:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('PROCESANDO', 'Procesando'), ('PAGADO', 'Pagado')], default='ABIERTO', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Período de Liquidación',
                'verbose_name_plural': 'Períodos de Liquidación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='trabajador',
            name='afp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='plan_salud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='sistema_salud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISADA', 'Revisada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20)),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=0)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonificacion_colacion', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bonificacion_movilidad', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('otros_bonos', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_haberes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_revisadas', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='rrhh.trabajador')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='rrhh.periodoliquidacion')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-periodo__fecha_inicio', 'trabajador__usuario__last_name'],
                'unique_together': {('periodo', 'trabajador')},
            },
        ),
        migrations.CreateModel(
            name='DetalleDescuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('obligatorio', models.BooleanField(default=True, help_text='Indica si es un descuento legal obligatorio')),
                ('observacion', models.TextField(blank=True)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='rrhh.liquidacion')),
            ],
            options={
                'verbose_name': 'Detalle de Descuento',
                'verbose_name_plural': 'Detalles de Descuentos',
            },
        ),
        migrations.CreateModel(
            name='DetalleBonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('permanente', models.BooleanField(default=False, help_text='Indica si la bonificación es permanente')),
                ('observacion', models.TextField(blank=True)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones', to='rrhh.liquidacion')),
            ],
            options={
                'verbose_name': 'Detalle de Bonificación',
                'verbose_name_plural': 'Detalles de Bonificaciones',
            },
        ),
    ]
