# Generated by Django 5.1.4 on 2025-01-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_periodoliquidacion_trabajador_afp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='banco',
            field=models.CharField(blank=True, choices=[('ESTADO', 'Banco Estado'), ('CHILE', 'Banco de Chile'), ('BCI', 'Banco BCI'), ('SANTANDER', 'Banco Santander'), ('SCOTIABANK', 'Banco Scotiabank'), ('ITAU', 'Banco Itaú'), ('FALABELLA', 'Banco Falabella'), ('SECURITY', 'Banco Security')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('CORRIENTE', 'Cuenta Corriente'), ('VISTA', 'Cuenta Vista'), ('AHORRO', 'Cuenta de Ahorro'), ('RUT', 'Cuenta RUT')], max_length=50, null=True),
        ),
    ]
